name: dk_util
description: DorkyTiger's Flutter utility library with logging, state management and more
version: 1.0.0

homepage: https://github.com/dorkytiger/dk_util

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  file_picker: ^10.3.8
  web_socket_channel: ^3.0.3
  nsd: ^4.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

